Year 1 Revenue Mix:
  government_contracts: 0.4
  international_partnerships: 0.3
  private_consulting: 0.2
  grants_donations: 0.1
  total_target: 1228000

Year 3 Revenue Mix:
  government_contracts: 0.35
  international_partnerships: 0.25
  private_consulting: 0.25
  grants_donations: 0.05
  intellectual_property: 0.1
  total_target: 1850000

Year 5 Revenue Mix:
  government_contracts: 0.3
  international_partnerships: 0.2
  private_consulting: 0.3
  grants_donations: 0.05
  intellectual_property: 0.15
  total_target: 2500000
